# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - VM-1*

pool:
  name: "On Premise - BT-INFRA - LINUX"

steps:
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    SourceFolder: .
    CleanTargetFolder: True
    Contents: |
      kubernetes/**
      !*/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: Majkubernetes1
